// Curated burned + museum CryptoPunks + known vault wallets from
// data/curated.json (generated by scripts/gen-curated.mjs from the BurnedPunks,
// MuseumPunks, and LostPunks projects). Fetched once and cached:
// { burnedBase, museumBase, burned:{id:{intent,by}}, museum:{id:{name}},
//   vaults:{address:{label}} }.
let cache = null;

export function fetchCurated() {
  if (!cache) cache = fetch("/data/curated.json").then((r) => (r.ok ? r.json() : null)).catch(() => null);
  return cache;
}
