// Local punk image rendering from the static pixel bundle generated by
// scripts/gen-pixels.mjs (from @networked-art/punks-sdk offline data). Renders
// a punk's 24x24 indexed pixels to a PNG data URI via canvas — no external
// image host, no SDK/viem in the browser. The bundle (~593K gzip) is fetched
// once on the first render and cached; every punk after is instant.
let ready = null;

function prepare(d) {
  if (!d || !d.pixels) return null;
  const bin = atob(d.pixels);
  const px = new Uint8Array(bin.length);
  for (let i = 0; i < bin.length; i++) px[i] = bin.charCodeAt(i);
  // "RRGGBBAA" hex -> [r,g,b,a]
  const pal = d.palette.map((h) => [
    parseInt(h.slice(0, 2), 16),
    parseInt(h.slice(2, 4), 16),
    parseInt(h.slice(4, 6), 16),
    parseInt(h.slice(6, 8), 16),
  ]);
  return { w: d.w, h: d.h, total: d.total, px, pal };
}

function load() {
  if (!ready) {
    ready = fetch("/data/punks-pixels.json")
      .then((r) => (r.ok ? r.json() : null))
      .then(prepare)
      .catch(() => null);
  }
  return ready;
}

// PNG data URI for a punk id, or null if the bundle isn't available. The image
// is 24x24; CSS (image-rendering: pixelated) scales it crisply.
export async function renderPunkDataUri(id) {
  const b = await load();
  if (!b || !Number.isInteger(id) || id < 0 || id >= b.total) return null;
  const { w, h, px, pal } = b;
  const off = id * w * h;
  const canvas = document.createElement("canvas");
  canvas.width = w;
  canvas.height = h;
  const ctx = canvas.getContext("2d");
  const img = ctx.createImageData(w, h);
  for (let i = 0; i < w * h; i++) {
    const c = pal[px[off + i]] || [0, 0, 0, 0];
    img.data[i * 4] = c[0];
    img.data[i * 4 + 1] = c[1];
    img.data[i * 4 + 2] = c[2];
    img.data[i * 4 + 3] = c[3];
  }
  ctx.putImageData(img, 0, 0);
  return canvas.toDataURL("image/png");
}
