// Per-punk traits + rarity from the static dataset generated by
// scripts/gen-traits.mjs (from the @networked-art/punks-sdk offline data).
// Fetched once and cached; each entry is { t: type, a: [accessories], n:
// attribute count, r: rarity rank }.
let bundle = null;

function loadAll() {
  if (!bundle) bundle = fetch("/data/punks-traits.json").then((r) => (r.ok ? r.json() : null)).catch(() => null);
  return bundle;
}

export async function getTraits(id) {
  const d = await loadAll();
  return d?.punks?.[id] || null;
}
